//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelExporterImporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelExporterImporter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical Model Objects.
        /// </summary>
        public static string AnalyticalModelObjects {
            get {
                return ResourceManager.GetString("AnalyticalModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Objects.
        /// </summary>
        public static string AnnotationObjects {
            get {
                return ResourceManager.GetString("AnnotationObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this process?.
        /// </summary>
        public static string AreYouSureYouWantCancelProcess {
            get {
                return ResourceManager.GetString("AreYouSureYouWantCancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible for import.
        /// </summary>
        public static string AvailableImport {
            get {
                return ResourceManager.GetString("AvailableImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the export process.
        /// </summary>
        public static string CancelTheExportProcess {
            get {
                return ResourceManager.GetString("CancelTheExportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server.
        /// </summary>
        public static string CannotConnectToServeur {
            get {
                return ResourceManager.GetString("CannotConnectToServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert ParameterType.
        /// </summary>
        public static string CannotConvertParameterType {
            get {
                return ResourceManager.GetString("CannotConvertParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check None.
        /// </summary>
        public static string CheckNone {
            get {
                return ResourceManager.GetString("CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string clColTitleColor {
            get {
                return ResourceManager.GetString("clColTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string clColTitleDescription {
            get {
                return ResourceManager.GetString("clColTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the value of the parameter is allowed.
        /// </summary>
        public static string clDescChangingValueParameterAllowed {
            get {
                return ResourceManager.GetString("clDescChangingValueParameterAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column title.
        /// </summary>
        public static string clDescColumnTitle {
            get {
                return ResourceManager.GetString("clDescColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value locked and which cannot be modified for import.
        /// </summary>
        public static string clDescParameterValueLocked {
            get {
                return ResourceManager.GetString("clDescParameterValueLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-total level 1.
        /// </summary>
        public static string clDescSubTotalLevel1 {
            get {
                return ResourceManager.GetString("clDescSubTotalLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub total level 2 and above.
        /// </summary>
        public static string clDescSubTotalLevel2 {
            get {
                return ResourceManager.GetString("clDescSubTotalLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string clDescTotal {
            get {
                return ResourceManager.GetString("clDescTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of a locked item type parameter.
        /// </summary>
        public static string clDescValueLockedElementType {
            get {
                return ResourceManager.GetString("clDescValueLockedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of a parameter which cannot be exported.
        /// </summary>
        public static string clDescValueParameterNotExported {
            get {
                return ResourceManager.GetString("clDescValueParameterNotExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type.
        /// </summary>
        public static string clDescValueType {
            get {
                return ResourceManager.GetString("clDescValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for more information.
        /// </summary>
        public static string ClickHereForMoreInformation {
            get {
                return ResourceManager.GetString("ClickHereForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string clLegend {
            get {
                return ResourceManager.GetString("clLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color legend.
        /// </summary>
        public static string clLegendTitle {
            get {
                return ResourceManager.GetString("clLegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with errors.
        /// </summary>
        public static string CompletedWithErrors {
            get {
                return ResourceManager.GetString("CompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Save.
        /// </summary>
        public static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Do you want to replace it?.
        /// </summary>
        public static string ConfirmSaveMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file {0}, the process cannot continue. If the file is currently open, you must close it to continue..
        /// </summary>
        public static string CouldNotDeleteFile {
            get {
                return ResourceManager.GetString("CouldNotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Pattern.
        /// </summary>
        public static string CutPattern {
            get {
                return ResourceManager.GetString("CutPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Pattern Color (R-G-B).
        /// </summary>
        public static string CutPatternColorRGB {
            get {
                return ResourceManager.GetString("CutPatternColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need help? Do you want to report an issue?.
        /// </summary>
        public static string DoYouNeedHelp {
            get {
                return ResourceManager.GetString("DoYouNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while setting parameter {0} : {1}.
        /// </summary>
        public static string ErrorOccurredWhileSettingParameter {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting data: {0}
        ///.
        /// </summary>
        public static string ExportErrorMessage {
            get {
                return ResourceManager.GetString("ExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export mode.
        /// </summary>
        public static string ExportMode {
            get {
                return ResourceManager.GetString("ExportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export process was completed successfully..
        /// </summary>
        public static string ExportProcessCompleteMessage {
            get {
                return ResourceManager.GetString("ExportProcessCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting &quot;{0}&quot;.
        /// </summary>
        public static string ExportProgressExporting {
            get {
                return ResourceManager.GetString("ExportProgressExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Listing.
        /// </summary>
        public static string FamilyListing {
            get {
                return ResourceManager.GetString("FamilyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File :.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action can&apos;t be completed because the file is open in another program. Close the file and try again..
        /// </summary>
        public static string FileInUseMessage {
            get {
                return ResourceManager.GetString("FileInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File In Use.
        /// </summary>
        public static string FileInUseTitle {
            get {
                return ResourceManager.GetString("FileInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Elements From Excel File.
        /// </summary>
        public static string ImportElementFormExcelFile {
            get {
                return ResourceManager.GetString("ImportElementFormExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing data: {0}.
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing element: {0} ({1}).
        /// </summary>
        public static string ImportingElement {
            get {
                return ResourceManager.GetString("ImportingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to import data from..
        /// </summary>
        public static string ImportNoFileSelected {
            get {
                return ResourceManager.GetString("ImportNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        public static string ImportNoFileSelectedTitle {
            get {
                return ResourceManager.GetString("ImportNoFileSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select worksheet(s) to import..
        /// </summary>
        public static string ImportNoSelection {
            get {
                return ResourceManager.GetString("ImportNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string ImportNoSelectionTitle {
            get {
                return ResourceManager.GetString("ImportNoSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import process was completed successfully..
        /// </summary>
        public static string ImportProcessCompleteMessage {
            get {
                return ResourceManager.GetString("ImportProcessCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import unavailable.
        /// </summary>
        public static string ImportUnavailable {
            get {
                return ResourceManager.GetString("ImportUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data that can be imported..
        /// </summary>
        public static string ImportUnavailableMsg {
            get {
                return ResourceManager.GetString("ImportUnavailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Binding.
        /// </summary>
        public static string InstanceBinding {
            get {
                return ResourceManager.GetString("InstanceBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid excel file.
        /// </summary>
        public static string InvalidExcelFile {
            get {
                return ResourceManager.GetString("InvalidExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use an excel file that has been exported by this component. See help for more information..
        /// </summary>
        public static string InvalidExcelFileMessage {
            get {
                return ResourceManager.GetString("InvalidExcelFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a known standard guid..
        /// </summary>
        public static string IsNotKnownStandardGuid {
            get {
                return ResourceManager.GetString("IsNotKnownStandardGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Shared.
        /// </summary>
        public static string IsShared {
            get {
                return ResourceManager.GetString("IsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Color (R,G,B).
        /// </summary>
        public static string LineColorRGB {
            get {
                return ResourceManager.GetString("LineColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Styles.
        /// </summary>
        public static string LineStyles {
            get {
                return ResourceManager.GetString("LineStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Weight - Cut.
        /// </summary>
        public static string LineWeightCut {
            get {
                return ResourceManager.GetString("LineWeightCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Weight - Projection.
        /// </summary>
        public static string LineWeightProjection {
            get {
                return ResourceManager.GetString("LineWeightProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials (All used).
        /// </summary>
        public static string MaterialsAllUsed {
            get {
                return ResourceManager.GetString("MaterialsAllUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Objects.
        /// </summary>
        public static string ModelObjects {
            get {
                return ResourceManager.GetString("ModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not compatible for import.
        /// </summary>
        public static string NotAvailableForImport {
            get {
                return ResourceManager.GetString("NotAvailableForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select schedule(s) or standard(s) to export..
        /// </summary>
        public static string NothingToExportMessage {
            get {
                return ResourceManager.GetString("NothingToExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Selection.
        /// </summary>
        public static string NothingToExportTitle {
            get {
                return ResourceManager.GetString("NothingToExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirectional - Import possible but modified formatting..
        /// </summary>
        public static string NoticeExportAvanced {
            get {
                return ResourceManager.GetString("NoticeExportAvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidirectional - Keeps formatting but import impossible..
        /// </summary>
        public static string NoticeExportBasic {
            get {
                return ResourceManager.GetString("NoticeExportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the import of data via an exported schedule in bidirectional mode..
        /// </summary>
        public static string NoticeImport {
            get {
                return ResourceManager.GetString("NoticeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Styles.
        /// </summary>
        public static string ObjectStyles {
            get {
                return ResourceManager.GetString("ObjectStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file, one tab per schedule.
        /// </summary>
        public static string OneFileOneTabPerSchedule {
            get {
                return ResourceManager.GetString("OneFileOneTabPerSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One file per schedule.
        /// </summary>
        public static string OneFilePerSchedule {
            get {
                return ResourceManager.GetString("OneFilePerSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Open a ticket.
        /// </summary>
        public static string OpenATicket {
            get {
                return ResourceManager.GetString("OpenATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder :.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite target files.
        /// </summary>
        public static string OverwriteTargetFiles {
            get {
                return ResourceManager.GetString("OverwriteTargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite the existing files.
        /// </summary>
        public static string OverwriteTheExistingFiles {
            get {
                return ResourceManager.GetString("OverwriteTheExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Group Name.
        /// </summary>
        public static string OwnerGroupName {
            get {
                return ResourceManager.GetString("OwnerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix :.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Complete.
        /// </summary>
        public static string ProcessCompleteTitle {
            get {
                return ResourceManager.GetString("ProcessCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Excel data....
        /// </summary>
        public static string ProgressImportingExcelData {
            get {
                return ResourceManager.GetString("ProgressImportingExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Parameters.
        /// </summary>
        public static string ProjectParameters {
            get {
                return ResourceManager.GetString("ProjectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Parameters Settings.
        /// </summary>
        public static string ProjectParametersSettings {
            get {
                return ResourceManager.GetString("ProjectParametersSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule {0} : {1}.
        /// </summary>
        public static string Schedule2 {
            get {
                return ResourceManager.GetString("Schedule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a destination folder..
        /// </summary>
        public static string SelectTargetFolderMessage {
            get {
                return ResourceManager.GetString("SelectTargetFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Folder is Empty.
        /// </summary>
        public static string SelectTargetFolderTitle {
            get {
                return ResourceManager.GetString("SelectTargetFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading Color (R-G-B).
        /// </summary>
        public static string ShadingColorRGB {
            get {
                return ResourceManager.GetString("ShadingColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Parameters Settings.
        /// </summary>
        public static string SharedParametersSettings {
            get {
                return ResourceManager.GetString("SharedParametersSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Project Parameters.
        /// </summary>
        public static string SharedProjectParameters {
            get {
                return ResourceManager.GetString("SharedProjectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Listing.
        /// </summary>
        public static string SheetListing {
            get {
                return ResourceManager.GetString("SheetListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Listing (All).
        /// </summary>
        public static string SheetListingAll {
            get {
                return ResourceManager.GetString("SheetListingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        public static string SheetNumber {
            get {
                return ResourceManager.GetString("SheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some elements could not be imported..
        /// </summary>
        public static string SomeElementsCouldNotBeImported {
            get {
                return ResourceManager.GetString("SomeElementsCouldNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard {0} : {1}.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standards.
        /// </summary>
        public static string Standards {
            get {
                return ResourceManager.GetString("Standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Pattern.
        /// </summary>
        public static string SurfacePattern {
            get {
                return ResourceManager.GetString("SurfacePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Pattern Alignment.
        /// </summary>
        public static string SurfacePatternAlignment {
            get {
                return ResourceManager.GetString("SurfacePatternAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Pattern Color (R-G-B).
        /// </summary>
        public static string SurfacePatternColorRGB {
            get {
                return ResourceManager.GetString("SurfacePatternColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export (Advanced).
        /// </summary>
        public static string TabExportAdvanced {
            get {
                return ResourceManager.GetString("TabExportAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export (Basic).
        /// </summary>
        public static string TabExportBasic {
            get {
                return ResourceManager.GetString("TabExportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file(s) already exists.
        /// </summary>
        public static string TargetFileAlreadyExists {
            get {
                return ResourceManager.GetString("TargetFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists..
        /// </summary>
        public static string TheFileAlreadyExists {
            get {
                return ResourceManager.GetString("TheFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import process was completed with errors..
        /// </summary>
        public static string TheImportProcessWasCompletedWithErrors {
            get {
                return ResourceManager.GetString("TheImportProcessWasCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target folder already contains {0} files with conflicting names.
        /// </summary>
        public static string TheTargetFolderAlreadyContainsFiles {
            get {
                return ResourceManager.GetString("TheTargetFolderAlreadyContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sheet can not be imported..
        /// </summary>
        public static string ThisSheetCanNotBeImported {
            get {
                return ResourceManager.GetString("ThisSheetCanNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string TitleBtnExport {
            get {
                return ResourceManager.GetString("TitleBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string TitleBtnImport {
            get {
                return ResourceManager.GetString("TitleBtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to a UnitType..
        /// </summary>
        public static string ToAUnitType {
            get {
                return ResourceManager.GetString("ToAUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a corresponding value for the specified text ({0})..
        /// </summary>
        public static string UnableFindCorrespondingValue {
            get {
                return ResourceManager.GetString("UnableFindCorrespondingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file.
        /// </summary>
        public static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Render Appearance for Shading.
        /// </summary>
        public static string UseRenderAppearanceForShading {
            get {
                return ResourceManager.GetString("UseRenderAppearanceForShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Modifiable.
        /// </summary>
        public static string UserModifiable {
            get {
                return ResourceManager.GetString("UserModifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Listing.
        /// </summary>
        public static string ViewListing {
            get {
                return ResourceManager.GetString("ViewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Listing (All).
        /// </summary>
        public static string ViewListingAll {
            get {
                return ResourceManager.GetString("ViewListingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Name.
        /// </summary>
        public static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The values of formula columns are not exported in advanced mode. You can use the basic mode to export the results of the formula..
        /// </summary>
        public static string WarningFormula {
            get {
                return ResourceManager.GetString("WarningFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current document contains unsaved changes. Please save the current file and try again..
        /// </summary>
        public static string WarningRevitFileNotSaved {
            get {
                return ResourceManager.GetString("WarningRevitFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Saved.
        /// </summary>
        public static string WarningRevitFileNotSavedTitle {
            get {
                return ResourceManager.GetString("WarningRevitFileNotSavedTitle", resourceCulture);
            }
        }
    }
}
