//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelExporterImporter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelExporterImporter.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets du modèle analytique.
        /// </summary>
        public static string AnalyticalModelObjects {
            get {
                return ResourceManager.GetString("AnalyticalModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets d&apos;annotation.
        /// </summary>
        public static string AnnotationObjects {
            get {
                return ResourceManager.GetString("AnnotationObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment annuler ce processus ?.
        /// </summary>
        public static string AreYouSureYouWantCancelProcess {
            get {
                return ResourceManager.GetString("AreYouSureYouWantCancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible pour l&apos;import.
        /// </summary>
        public static string AvailableImport {
            get {
                return ResourceManager.GetString("AvailableImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulation....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler le processus d&apos;exportation.
        /// </summary>
        public static string CancelTheExportProcess {
            get {
                return ResourceManager.GetString("CancelTheExportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion au serveur impossible.
        /// </summary>
        public static string CannotConnectToServeur {
            get {
                return ResourceManager.GetString("CannotConnectToServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de convertir le type de paramètre.
        /// </summary>
        public static string CannotConvertParameterType {
            get {
                return ResourceManager.GetString("CannotConvertParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout cocher.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rien cocher.
        /// </summary>
        public static string CheckNone {
            get {
                return ResourceManager.GetString("CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur.
        /// </summary>
        public static string clColTitleColor {
            get {
                return ResourceManager.GetString("clColTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string clColTitleDescription {
            get {
                return ResourceManager.GetString("clColTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification de la valeur du paramètre est autorisé.
        /// </summary>
        public static string clDescChangingValueParameterAllowed {
            get {
                return ResourceManager.GetString("clDescChangingValueParameterAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre de la colonne.
        /// </summary>
        public static string clDescColumnTitle {
            get {
                return ResourceManager.GetString("clDescColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur du paramètre verrouillé et qui ne peut être modifié pour l&apos;importation.
        /// </summary>
        public static string clDescParameterValueLocked {
            get {
                return ResourceManager.GetString("clDescParameterValueLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous total niveau 1.
        /// </summary>
        public static string clDescSubTotalLevel1 {
            get {
                return ResourceManager.GetString("clDescSubTotalLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous total niveau 2 et plus.
        /// </summary>
        public static string clDescSubTotalLevel2 {
            get {
                return ResourceManager.GetString("clDescSubTotalLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string clDescTotal {
            get {
                return ResourceManager.GetString("clDescTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur d&apos;un paramètre de type d&apos;élément verrouillé.
        /// </summary>
        public static string clDescValueLockedElementType {
            get {
                return ResourceManager.GetString("clDescValueLockedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur d&apos;un paramètre qui ne peut être exporté.
        /// </summary>
        public static string clDescValueParameterNotExported {
            get {
                return ResourceManager.GetString("clDescValueParameterNotExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de valeur.
        /// </summary>
        public static string clDescValueType {
            get {
                return ResourceManager.GetString("clDescValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez ici pour plus d&apos;information.
        /// </summary>
        public static string ClickHereForMoreInformation {
            get {
                return ResourceManager.GetString("ClickHereForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Légende.
        /// </summary>
        public static string clLegend {
            get {
                return ResourceManager.GetString("clLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Légende des couleurs.
        /// </summary>
        public static string clLegendTitle {
            get {
                return ResourceManager.GetString("clLegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé avec des erreurs.
        /// </summary>
        public static string CompletedWithErrors {
            get {
                return ResourceManager.GetString("CompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer l&apos;enregistrement.
        /// </summary>
        public static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} existe déjà. Voulez-vous le remplacer ?.
        /// </summary>
        public static string ConfirmSaveMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le fichier {0}, le processus ne peut pas continuer. Si le fichier est présentement ouvert, vous devez le fermer pour poursuivre..
        /// </summary>
        public static string CouldNotDeleteFile {
            get {
                return ResourceManager.GetString("CouldNotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif de coupe.
        /// </summary>
        public static string CutPattern {
            get {
                return ResourceManager.GetString("CutPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur du motif de coupe (R-G-B).
        /// </summary>
        public static string CutPatternColorRGB {
            get {
                return ResourceManager.GetString("CutPatternColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous besoin d&apos;aide? Souhaitez-vous signaler un problème ?.
        /// </summary>
        public static string DoYouNeedHelp {
            get {
                return ResourceManager.GetString("DoYouNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de la définition du paramètre {0}: {1}.
        /// </summary>
        public static string ErrorOccurredWhileSettingParameter {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORTER.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;exportation des données: {0}.
        /// </summary>
        public static string ExportErrorMessage {
            get {
                return ResourceManager.GetString("ExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation de {0}.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode d&apos;export.
        /// </summary>
        public static string ExportMode {
            get {
                return ResourceManager.GetString("ExportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options d&apos;exportation.
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le processus d&apos;exportation s&apos;est terminé avec succès..
        /// </summary>
        public static string ExportProcessCompleteMessage {
            get {
                return ResourceManager.GetString("ExportProcessCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportation &quot;{0}&quot;.
        /// </summary>
        public static string ExportProgressExporting {
            get {
                return ResourceManager.GetString("ExportProgressExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des familles.
        /// </summary>
        public static string FamilyListing {
            get {
                return ResourceManager.GetString("FamilyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier :.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;action ne peut pas être terminée, car le fichier est ouvert dans un autre programme. Fermez le fichier et réessayez..
        /// </summary>
        public static string FileInUseMessage {
            get {
                return ResourceManager.GetString("FileInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier en cours d&apos;utilisation.
        /// </summary>
        public static string FileInUseTitle {
            get {
                return ResourceManager.GetString("FileInUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphique.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTER.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer des éléments depuis un fichier Excel.
        /// </summary>
        public static string ImportElementFormExcelFile {
            get {
                return ResourceManager.GetString("ImportElementFormExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;importation des données: {0}.
        /// </summary>
        public static string ImportErrorMessage {
            get {
                return ResourceManager.GetString("ImportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élément importé : {0} ({1}).
        /// </summary>
        public static string ImportingElement {
            get {
                return ResourceManager.GetString("ImportingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un fichier pour importer les données..
        /// </summary>
        public static string ImportNoFileSelected {
            get {
                return ResourceManager.GetString("ImportNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier sélectionné.
        /// </summary>
        public static string ImportNoFileSelectedTitle {
            get {
                return ResourceManager.GetString("ImportNoFileSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner les feuilles de calcul à importer..
        /// </summary>
        public static string ImportNoSelection {
            get {
                return ResourceManager.GetString("ImportNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string ImportNoSelectionTitle {
            get {
                return ResourceManager.GetString("ImportNoSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le processus d&apos;importation s&apos;est terminé avec succès..
        /// </summary>
        public static string ImportProcessCompleteMessage {
            get {
                return ResourceManager.GetString("ImportProcessCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importation non disponible.
        /// </summary>
        public static string ImportUnavailable {
            get {
                return ResourceManager.GetString("ImportUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucune donnée qui peut être importée..
        /// </summary>
        public static string ImportUnavailableMsg {
            get {
                return ResourceManager.GetString("ImportUnavailableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liaison d&apos;instance.
        /// </summary>
        public static string InstanceBinding {
            get {
                return ResourceManager.GetString("InstanceBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier Excel non valide.
        /// </summary>
        public static string InvalidExcelFile {
            get {
                return ResourceManager.GetString("InvalidExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez utiliser un fichier Excel qui a été exporté par ce composant. Consultez l&apos;aide pour en savoir plus..
        /// </summary>
        public static string InvalidExcelFileMessage {
            get {
                return ResourceManager.GetString("InvalidExcelFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas un guide standard connu..
        /// </summary>
        public static string IsNotKnownStandardGuid {
            get {
                return ResourceManager.GetString("IsNotKnownStandardGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est partagé.
        /// </summary>
        public static string IsShared {
            get {
                return ResourceManager.GetString("IsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur de la ligne (R,G,B).
        /// </summary>
        public static string LineColorRGB {
            get {
                return ResourceManager.GetString("LineColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles de ligne.
        /// </summary>
        public static string LineStyles {
            get {
                return ResourceManager.GetString("LineStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Épaisseur de la  ligne - Coupe.
        /// </summary>
        public static string LineWeightCut {
            get {
                return ResourceManager.GetString("LineWeightCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Épaisseur de la ligne - Projection.
        /// </summary>
        public static string LineWeightProjection {
            get {
                return ResourceManager.GetString("LineWeightProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériaux.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériaux (Tous utilisés).
        /// </summary>
        public static string MaterialsAllUsed {
            get {
                return ResourceManager.GetString("MaterialsAllUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets de modèle.
        /// </summary>
        public static string ModelObjects {
            get {
                return ResourceManager.GetString("ModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version à jour.
        /// </summary>
        public static string NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("NoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non compatible pour l&apos;import.
        /// </summary>
        public static string NotAvailableForImport {
            get {
                return ResourceManager.GetString("NotAvailableForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner les programmes ou les normes à exporter..
        /// </summary>
        public static string NothingToExportMessage {
            get {
                return ResourceManager.GetString("NothingToExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection vide.
        /// </summary>
        public static string NothingToExportTitle {
            get {
                return ResourceManager.GetString("NothingToExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidirectionnel - L&apos;import possible, mais la mise en forme est modifiée..
        /// </summary>
        public static string NoticeExportAvanced {
            get {
                return ResourceManager.GetString("NoticeExportAvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidirectionnel - Conserve la mise en forme, mais l&apos;import est impossible..
        /// </summary>
        public static string NoticeExportBasic {
            get {
                return ResourceManager.GetString("NoticeExportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permets l&apos;import de données via une nomenclature exportée en mode bidirectionnel..
        /// </summary>
        public static string NoticeImport {
            get {
                return ResourceManager.GetString("NoticeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles d&apos;objets.
        /// </summary>
        public static string ObjectStyles {
            get {
                return ResourceManager.GetString("ObjectStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un fichier, un onglet par nomenclature.
        /// </summary>
        public static string OneFileOneTabPerSchedule {
            get {
                return ResourceManager.GetString("OneFileOneTabPerSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un fichier par nomenclature.
        /// </summary>
        public static string OneFilePerSchedule {
            get {
                return ResourceManager.GetString("OneFilePerSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ouvrir un billet.
        /// </summary>
        public static string OpenATicket {
            get {
                return ResourceManager.GetString("OpenATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire de sortie :.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écraser les fichiers cibles.
        /// </summary>
        public static string OverwriteTargetFiles {
            get {
                return ResourceManager.GetString("OverwriteTargetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Écraser les fichiers existants.
        /// </summary>
        public static string OverwriteTheExistingFiles {
            get {
                return ResourceManager.GetString("OverwriteTheExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du groupe propriétaires.
        /// </summary>
        public static string OwnerGroupName {
            get {
                return ResourceManager.GetString("OwnerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préfixe :.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération terminée.
        /// </summary>
        public static string ProcessCompleteTitle {
            get {
                return ResourceManager.GetString("ProcessCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer des données Excel ....
        /// </summary>
        public static string ProgressImportingExcelData {
            get {
                return ResourceManager.GetString("ProgressImportingExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur le projet.
        /// </summary>
        public static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres du projet.
        /// </summary>
        public static string ProjectParameters {
            get {
                return ResourceManager.GetString("ProjectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres du projet.
        /// </summary>
        public static string ProjectParametersSettings {
            get {
                return ResourceManager.GetString("ProjectParametersSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétés.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature {0} : {1}.
        /// </summary>
        public static string Schedule2 {
            get {
                return ResourceManager.GetString("Schedule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner un dossier de destination..
        /// </summary>
        public static string SelectTargetFolderMessage {
            get {
                return ResourceManager.GetString("SelectTargetFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le dossier cible est vide.
        /// </summary>
        public static string SelectTargetFolderTitle {
            get {
                return ResourceManager.GetString("SelectTargetFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur d&apos;ombrage (R-G-B).
        /// </summary>
        public static string ShadingColorRGB {
            get {
                return ResourceManager.GetString("ShadingColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres partagés.
        /// </summary>
        public static string SharedParametersSettings {
            get {
                return ResourceManager.GetString("SharedParametersSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres de projet partagés.
        /// </summary>
        public static string SharedProjectParameters {
            get {
                return ResourceManager.GetString("SharedProjectParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des feuilles.
        /// </summary>
        public static string SheetListing {
            get {
                return ResourceManager.GetString("SheetListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des feuilles (Toutes).
        /// </summary>
        public static string SheetListingAll {
            get {
                return ResourceManager.GetString("SheetListingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la feuille.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de feuille.
        /// </summary>
        public static string SheetNumber {
            get {
                return ResourceManager.GetString("SheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certains éléments n&apos;ont pas pu être importés..
        /// </summary>
        public static string SomeElementsCouldNotBeImported {
            get {
                return ResourceManager.GetString("SomeElementsCouldNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard {0} : {1}.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standards.
        /// </summary>
        public static string Standards {
            get {
                return ResourceManager.GetString("Standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif de surface.
        /// </summary>
        public static string SurfacePattern {
            get {
                return ResourceManager.GetString("SurfacePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement du motif de surface.
        /// </summary>
        public static string SurfacePatternAlignment {
            get {
                return ResourceManager.GetString("SurfacePatternAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur du motif de surface (R-G-B).
        /// </summary>
        public static string SurfacePatternColorRGB {
            get {
                return ResourceManager.GetString("SurfacePatternColorRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter (Avancé).
        /// </summary>
        public static string TabExportAdvanced {
            get {
                return ResourceManager.GetString("TabExportAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter (Base).
        /// </summary>
        public static string TabExportBasic {
            get {
                return ResourceManager.GetString("TabExportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ou les fichiers cibles existent déjà.
        /// </summary>
        public static string TargetFileAlreadyExists {
            get {
                return ResourceManager.GetString("TargetFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0} existe déjà..
        /// </summary>
        public static string TheFileAlreadyExists {
            get {
                return ResourceManager.GetString("TheFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le processus d&apos;importation s&apos;est terminé avec des erreurs..
        /// </summary>
        public static string TheImportProcessWasCompletedWithErrors {
            get {
                return ResourceManager.GetString("TheImportProcessWasCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire cible contient déjà {0} fichiers avec des noms en conflit.
        /// </summary>
        public static string TheTargetFolderAlreadyContainsFiles {
            get {
                return ResourceManager.GetString("TheTargetFolderAlreadyContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette feuille ne peut être importée..
        /// </summary>
        public static string ThisSheetCanNotBeImported {
            get {
                return ResourceManager.GetString("ThisSheetCanNotBeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter.
        /// </summary>
        public static string TitleBtnExport {
            get {
                return ResourceManager.GetString("TitleBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string TitleBtnImport {
            get {
                return ResourceManager.GetString("TitleBtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à un type d&apos;unité..
        /// </summary>
        public static string ToAUnitType {
            get {
                return ResourceManager.GetString("ToAUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver une valeur correspondante pour le texte spécifié ({0})..
        /// </summary>
        public static string UnableFindCorrespondingValue {
            get {
                return ResourceManager.GetString("UnableFindCorrespondingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le fichier.
        /// </summary>
        public static string UnableToDeleteFile {
            get {
                return ResourceManager.GetString("UnableToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser l&apos;apparence de rendu pour l&apos;ombrage.
        /// </summary>
        public static string UseRenderAppearanceForShading {
            get {
                return ResourceManager.GetString("UseRenderAppearanceForShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiable par l&apos;utilisateur.
        /// </summary>
        public static string UserModifiable {
            get {
                return ResourceManager.GetString("UserModifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les détails.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des vues.
        /// </summary>
        public static string ViewListing {
            get {
                return ResourceManager.GetString("ViewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des vues (Toutes).
        /// </summary>
        public static string ViewListingAll {
            get {
                return ResourceManager.GetString("ViewListingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la vue.
        /// </summary>
        public static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement : Les valeurs des colonnes de type formule ne sont pas exportées dans le mode avancé. Vous pouvez utiliser le mode de base pour exporter les résultats de la formule..
        /// </summary>
        public static string WarningFormula {
            get {
                return ResourceManager.GetString("WarningFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le document actuel contient des modifications non enregistrées. Sauvegardez le fichier actuel et réessayez..
        /// </summary>
        public static string WarningRevitFileNotSaved {
            get {
                return ResourceManager.GetString("WarningRevitFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier non enregistré.
        /// </summary>
        public static string WarningRevitFileNotSavedTitle {
            get {
                return ResourceManager.GetString("WarningRevitFileNotSavedTitle", resourceCulture);
            }
        }
    }
}
